#!/bin/bash 
# Script to add a user to Linux system 
   
if [ $(id -u) -eq 0 ]; then
    read -p "Enter username : " username 
    read -s -p "Enter password : " password 
    egrep "^$username" /etc/passwd >/dev/null
    if [ $? -eq 0 ]; then
        echo "$username exists!"
        exit 1 
    else
#用perl语言中的 crypt加密函数对您输入的密码进行加密
        pass=$(perl -e 'print crypt($ARGV[0], "password")' $password) 
        useradd -m -p $pass $username 
#所填加的用户名是否成功
        [ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
    fi
else
    echo "Only root may add a user to the system"
    exit 2 
fi
